routes/web.php
<?php

use App\Http\Controllers\Backend\CategoryController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\Backend\DashboardController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return view('welcome');
});

 Route::get('/', 'HomeController@index')->name('home');
Route::prefix('users')->name('users.')->group(function(){   
    Route::get('/', [UsersController::class, 'index'])->name('index');

    Route::get('/add', [UsersController::class, 'add'])->name('add');

    Route::post('/add', [UsersController::class, 'postAdd'])->name('post-add');

    Route::get('/edit/{id}', [UsersController::class, 'getEdit'])->name('edit');

    Route::post('/edit/{id}', [UsersController::class, 'postEdit'])->name('post-edit');

    Route::get('/delete/{id}', [UsersController::class, 'delete'])->name('delete');

});

Route::namespace('Backend')->prefix('backend')->group(function() {
    Route::get('/', [DashboardController::class, 'index'] )->name('backend.dashboard.index');
    Route::get('product', 'ProductsController@index')->name('backend.products.index');
    Route::get('category', 'CategoryController@index')->name('backend.category.index');
    Route::get('news', 'NewsController@index')->name('backend.news.index');
    Route::get('users', 'UsersController@index')->name('backend.users.index');
}); 

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Users extends Model
{
    use HasFactory;

    protected $table = 'users';
    public $timestamps = false;
    protected $fillable = [
        'fullname',
        'email',
        'group_id',
        'update_at',
        'create_at',
    ];
    public function getAllUsers($perPage = null)
    {
        //$users = DB::select('SELECT * FROM users ORDER BY create_at DESC');
        $users = DB::table($this->table);

        if(!empty($perPage)){
            $users = $users->paginate($perPage);
        }else{
            $users = $users->get();
        }

        return $users;
    }
    
    public function addUser($data){
        DB::insert('INSERT INTO users (fullname, email, create_at, update_at, group_id) value (?, ?, ?, ?, ?)', $data);
    }

    public function getDetail($id){
       return DB::select('SELECT * FROM '.$this->table.' WHERE id = ?', [$id]);
    }

    public function updateUser($data, $id)
    {
        $data[] = $id;
        return DB::update('UPDATE '.$this->table.' SET fullname=?, email=?, update_at=? where id = ?', $data);
    }

    public function deleteUser($id){
        return DB::delete("DELETE FROM $this->table WHERE id=?", [$id]);
    }

    public function learnQueryBuilder()
    {
        DB::enableQueryLog();
        //Lấy tất cả bản ghi
        $id = 20;
        $lists = DB::table($this->table)
        ->select('fullname as hoten', 'email', 'id') 
          ->where('id', 19)
        ->where(function($query) use ($id){
            $query->where('id', '<', $id)->orWhere('id', '>', $id);
        }); 
        //->where('fullname', 'like', '%Hong%')
        //->whereBetween('id', [9, 10])
        //->whereIn('id', [8, 10])
        //->whereMonth('create_at', '03')

        //->get();
        //->toSql();

        //Join bảng
        //$lists = DB::table('users')
        //->select('users.*', 'groups.name as group_name')
        //->join('groups', 'users.group_id', '=', 'groups.id')
        //->select(DB::raw('count(id) as group_id'), 'email')
        //->groupBy('email')
        //->having('group_id', '>=', 2)
        //->get();

        //dd($lists);
        // $status = DB::table('users')->insert([
        //     'fullname' => 'Hong1246',
        //     'email' => 'nguyenvana@gmail.com',
        //    'group_id' => 1,
        //    'create_at' => date('Y-m-d H:i:s'),
        //]);
        //dd($status);
        //$lastId = DB::getPdo()->lastInsertId();
        //dd($lastId);

        $status = DB::table('users')
        ->where('id',17)
        ->update([
            'fullname' => 'Hong999',
            'email' => 'nguyenvana@gmail.com',
            'update_at' => date('Y-m-d H:i:s'),
        ]); 

         $status = DB::table('users')
        ->where('id', 13)
        ->delete(); 

        //$lists = DB::table('users')->where('id', '>', 20)->get();
        //$count = count($lists);
        //dd($count);

        $lists = DB::table('users')
        ->selectRaw('fullname, email')
        //->groupBy('email')
        ->orderByRaw('create_at DESC, update_at ASC')
        ->get();
        $sql = DB::getQueryLog();
        dd($sql);

        //Lấy bản ghi đầu tiên
        $detail = DB::table($this->table)->first();
    } 
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        return view('backend.users.index');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Users;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    protected $users;

    const _PER_PAGE = 4;
    public function __construct()
    {
        $this->users = new Users();

    }

    public function index()
    {
    $title = 'Danh sách người dùng';

    //$this->users->learnQueryBuilder();
    
    $users = new Users();

    $usersList = $users->getAllUsers(self::_PER_PAGE);

    return view('client.users.list', compact('title', 'usersList'));



    }

    public function add()
    {
        $title = 'Thêm người dùng';

        return view('client.users.add', compact('title'));
    }

    public function postAdd(Request $request)
    {
        $request->validate([
            'fullname' => 'required|min:5',
            'email' => 'required|email|unique:users'
        ], [
            'fullname.required' => 'Họ và tên bắt buộc phải nhập',
            'fullname.min' => 'Họ và tên phải từ :min kí tự trở lên',
            'email.required' => 'Email bắt buộc phải nhập',
            'email.email' => 'Email không đúng định dạng',
            'email.unique' => 'Email đã tồn tại trên hệ thống'
        ]);

        $dataInsert = [ 
            $request->fullname,
            $request->email,
            date('Y-m-d H:i:s') 
        ];
        $this->users->addUser($dataInsert);

        return redirect()->route('users.index')->with('Thêm người dùng thành công');
    }

    public function getEdit($id=0) {
        $title = 'Cập nhật người dùng người dùng';

        if(!empty($id)){
            $userDetail = $this->users->getDetail($id);
            if(!empty($userDetail[0])){
                $userDetail = $userDetail[0];
            }else{
                return redirect()->route('users.index');
            }
        }else{
            return redirect()->route('users.index');
        }

        return view('client.users.edit', compact('title', 'userDetail'));
    }
    public function postEdit(Request $request, $id){
        $request->validate([
            'fullname' => 'required|min:5',
            'email' => 'required|email',
        ], [
            'fullname.required' => 'Họ và tên bắt buộc phải nhập',
            'fullname.min' => 'Họ và tên phải từ :min kí tự trở lên',
            'email.required' => 'Email bắt buộc phải nhập',
            'email.email' => 'Email không đúng định dạng',
          //  'email.unique' => 'Email đã tồn tại trên hệ thống'
        ]);

        $dataUpdate = [ 
            $request->fullname,
            $request->email,
            date('Y-m-d H:i:s') 
        ];
        $this->users->updateUser($dataUpdate, $id);

        return redirect()->route('users.index', ['id'=>$id]);
    }

    public function delete($id = 0){
        if(!empty($id)){
            $userDetail = $this->users->getDetail($id);
            if(!empty($userDetail[0])){
                $deleteStatus = $this->users->deleteUser($id);
                if($deleteStatus){
                    $msg = 'Xóa thành công'; 
                }else{
                    $msg = 'Bạn không thể xóa';
                }
            }else{
                return redirect()->route('users.index');
            }
        }else{
            return redirect()->route('users.index');
        }
        return redirect()->route('users.index');
    }

    /* public function pagination()
    {
        return view('users.index', [
            'users' => DB::table('users')->paginate(15)
        ]);
    } */
}

resources/views/client/users/add.blade.php
@extends('layouts.master')

@section('page_title')
    User
@endsection

@section('main')
@if($errors->any())
<div class="alert alert-danger">Dữ liệu nhâp vào không hợp lệ</div>
@endif
<form action="" method="POST">
    <div class="mb-3">
        <label for="">Họ và tên</label><br>
        <input type="text" class="form-control" name="fullname" placeholder="Nhập họ và tên..." value="{{old('fullname')}}">
        @error('fullname')
        <span style="color:red">{{$message}}</span>
        @enderror
    </div>
    <div class="mb-3">
        <label for="">Email</label><br>
        <input type="text" class="form-control" name="email" placeholder="Nhập email..." value="{{old('email')}}">
        @error('email')
        <span style="color:red">{{$message}}</span>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary">Thêm mới</button>
    <a href="{{ route('users.index') }}" class="btn btn-primary">Quay lại</a>
    @csrf
</form>
@endsection

resources/views/client/users/edit.blade.php
@extends('layouts.master')

@section('page_title')
    User
@endsection

@section('main')
@if($errors->any())
<div class="alert alert-danger">Dữ liệu nhâp vào không hợp lệ</div>
@endif
<form action="" method="POST">
    <div class="mb-3">
        <label for="">Họ và tên</label><br>
        <input type="text" class="form-control" name="fullname" placeholder="Nhập họ và tên..." value="{{old('fullname') ?? $userDetail->fullname}}">
        @error('fullname')
        <span style="color:red">{{$message}}</span>
        @enderror
    </div>
    <div class="mb-3">
        <label for="">Email</label><br>
        <input type="text" class="form-control" name="email" placeholder="Nhập email..." value="{{old('email') ?? $userDetail->email}}">
        @error('email')
        <span style="color:red">{{$message}}</span>
        @enderror
    </div>
    <button type="submit" class="btn btn-primary">Cập nhật</button>
    <a href="{{ route('users.index') }}" class="btn btn-primary">Quay lại</a>
    @csrf
</form>
@endsection

resources/views/client/users/list.blade.php
@extends('layouts.master')

@section('page_title')
    User
@endsection
<style>
    .pagination{
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .page-item{
        margin-right: 10px;
    }
</style>
@section('main')
<h2>User</h2>
<a href="{{ route('users.add') }}" class="btn btn-primary">Thêm người dùng</a>
<hr />
<div class="gird-view">
    @if (!empty ($usersList))
    <table border="1" style="width: 600px">
        @foreach ($usersList as $key => $item)
        <tr>
            <td>{{$key+1}}</td>
            <td>{{$item->fullname}}</td>
            <td>{{$item->email}}</td>
            <td>{{$item->create_at}}</td>
            <td><a href="{{route('users.edit', ['id'=>$item->id])}}">Sửa</a></td>
            <td><a onclick="return confirm('Bạn có chắc chắn muốn xóa?')" href="{{route('users.delete', ['id'=>$item->id])}}">Xóa</a></td>
        </tr>
        @endforeach
    </table>
    @endif
    <div class="paginator" style="display: flex">
    {{$usersList->links()}}
    </div>
</div>
@endsection